/*
 * word.h
 *
 *  Created on: 17.04.2024
 *      Author: swt
 */

#ifndef WORD_H_
#define WORD_H_

#include <iostream>

std::string words[][10] = {{"PRADA","CHANEL","LANCOME","INTEL","HYUNDAI","GOOGLE","EBAY","PEPSI","COLGATE","PAMPERS"},
							{"MARMALADE","DRESSING","SESAME","TANGERINES","PRUNES","BUCKWHEAT","GARNISH","VEGETABLES","CUMIN","POLENTA"},
							{"COURIER","AUTHOR","DON","WORKMAN","APPRAISER","GRAMMARIAN","THERAPIST","REPORTER","MILLWRIGHT","SOLDIER"},
							{"TENNIS","DIAMOND","MOVEMENT","CANOE","SLALOM","FENCING","PADDLE","SKATE","TARGET","BATTLING"},
							{"SPRAY","INJECT","NAP","INFLUENCE","ENCODE","WAVER","DRONE","LISTEN","INTERRUPT","NOD"}};




#endif /* WORD_H_ */
